#!/usr/bin/env python3
"""Validate a single wiki page against the v2-hardened schema.

Usage:
    wiki-validate-page.py <page-path>
    wiki-validate-page.py --wiki-root <wiki-root> <page-path>

Checks performed in every mode:
  - Page has YAML frontmatter.
  - Required fields present: title, type, tags, sources, created, updated.
    (Phase B extends this with quality.* fields via a future patch.)
  - `type` membership checked against discovered categories (wiki-root mode only;
    Phase A: WARNING only; Phase D will flip to hard).
  - `created` and `updated` are full ISO-8601 UTC strings
    (e.g. 2026-04-24T13:00:00Z).
  - `tags` is a flat list.
  - `sources` is a flat list of strings (no nested mappings).

Additional checks when --wiki-root is given:
  - Every relative markdown link in the page body resolves to an existing file
    under the wiki root.
  - Every entry in `sources:` resolves to an existing file relative to the
    wiki root (skipped for a raw-file pointer that uses the literal string
    "conversation" -- that's handled in Phase B origin-tracking rules).
  - Depth >= 5 hard reject (Rule 2; always-on).

Exit codes:
  0 -- all checks pass
  1 -- one or more violations; each violation printed to stderr, one per line,
       prefixed with the page path.

Python 3.11+ required (for stdlib tomllib, though YAML parsing uses a tiny
vendored parser here to stay stdlib-only).
"""

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).parent))
from wiki_yaml import extract_frontmatter, parse_yaml

ISO_UTC_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")
REQUIRED_FIELDS_BASE = ("title", "type", "tags", "sources", "created", "updated")


def _discover(wiki_root: Path) -> dict:
    """Invoke wiki-discover.py; return its JSON output as a dict.

    Raises RuntimeError on discovery failure (validator exits non-zero on this).
    """
    script = Path(__file__).parent / "wiki-discover.py"
    result = subprocess.run(
        ["python3", str(script), "--wiki-root", str(wiki_root)],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"wiki-discover.py failed: {result.stderr.strip()}")
    return json.loads(result.stdout)


_LINK_RE = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")
_FENCED_CODE_RE = re.compile(r"```.*?```", re.DOTALL)
_INLINE_CODE_RE = re.compile(r"`[^`\n]+`")


def _extract_body_links(body: str) -> list[str]:
    """Return every (relative or absolute) URL target of a markdown link.

    Skips links that appear inside fenced code blocks (```...```) or inline
    code spans (`...`). Markdown link syntax inside code is illustrative,
    not a real link.
    """
    stripped = _FENCED_CODE_RE.sub("", body)
    stripped = _INLINE_CODE_RE.sub("", stripped)
    return _LINK_RE.findall(stripped)


def _is_external(link: str) -> bool:
    return (
        link.startswith("http://")
        or link.startswith("https://")
        or link.startswith("mailto:")
        or link.startswith("#")
    )


def validate(page_path: Path, wiki_root: Optional[Path] = None, disc: Optional[dict] = None) -> list[str]:
    """Return list of violation strings. Empty list = pass."""
    violations: list[str] = []
    if not page_path.is_file():
        return [f"{page_path}: file does not exist"]

    # v2.3: auto-generated MOC files (_index.md per directory + root index.md)
    # are not content pages — they have no frontmatter, no quality block, and
    # are regenerated by wiki-build-index.py. Skip validation entirely.
    if page_path.name == "_index.md":
        return []
    if wiki_root is not None and page_path.resolve() == (wiki_root / "index.md").resolve():
        return []

    # rel is used by v2.3-added stderr messages and violation strings.
    rel = str(page_path.relative_to(wiki_root)) if wiki_root is not None else str(page_path)

    text = page_path.read_text()
    fm = extract_frontmatter(text)
    if fm is None:
        return [f"{page_path}: no YAML frontmatter"]

    try:
        data = parse_yaml(fm)
    except ValueError as e:
        return [f"{page_path}: malformed frontmatter: {e}"]

    # Required fields
    for field in REQUIRED_FIELDS_BASE:
        if field not in data:
            violations.append(f"{page_path}: missing required field: {field}")

    # v2.3: type-membership check (Phase A: WARNING-only; Phase D will flip to hard).
    if "type" in data:
        t = data["type"]
        if disc is not None:
            discovered_types = set(disc["categories"])
            if t not in discovered_types:
                # PHASE_A_BEGIN
                print(
                    f"{rel}: WARNING type '{t}' not in discovered categories {sorted(discovered_types)}",
                    file=sys.stderr,
                )
                # PHASE_A_END
                # In Phase D's validator-flip task (Task 20), replace the print() above with:
                #     violations.append(f"{rel}: type '{t}' not in discovered categories {sorted(discovered_types)}")

            # Type vs path cross-check (Phase A: WARNING-only).
            if wiki_root is not None:
                expected_type = page_path.relative_to(wiki_root).parts[0]
                if t != expected_type:
                    # PHASE_A_BEGIN
                    print(
                        f"{rel}: WARNING type '{t}' != path.parts[0] '{expected_type}' "
                        f"(run: python3 scripts/wiki-fix-frontmatter.py --wiki-root {wiki_root} {rel})",
                        file=sys.stderr,
                    )
                    # PHASE_A_END
                    # In Phase D's validator-flip task (Task 20), replace the print() above with:
                    #     violations.append(f"{rel}: type '{t}' != path.parts[0] '{expected_type}' "
                    #                       f"(run: python3 scripts/wiki-fix-frontmatter.py --wiki-root {wiki_root} {rel})")

    # Depth >= 5 hard reject (Rule 2; always-on, no soft-warn period).
    if wiki_root is not None:
        rel_parts = page_path.relative_to(wiki_root).parts
        if len(rel_parts) > 5:
            violations.append(
                f"{rel}: page at depth {len(rel_parts)} exceeds hard cap (5); "
                f"place shallower or restructure category."
            )

    # dates
    for field in ("created", "updated"):
        if field in data:
            v = data[field]
            if not isinstance(v, str) or not ISO_UTC_RE.match(v):
                violations.append(
                    f"{page_path}: {field} must be ISO-8601 UTC "
                    f"(e.g. 2026-04-24T13:00:00Z), got {v!r}"
                )

    # tags flat list
    if "tags" in data:
        tags = data["tags"]
        if not isinstance(tags, list):
            violations.append(f"{page_path}: tags must be a list")
        else:
            for t in tags:
                if not isinstance(t, str):
                    violations.append(
                        f"{page_path}: every tag must be a string, got {t!r}"
                    )

    # sources flat list of strings (no nested maps)
    if "sources" in data:
        srcs = data["sources"]
        if not isinstance(srcs, list):
            violations.append(f"{page_path}: sources must be a flat list")
        else:
            for s in srcs:
                if isinstance(s, dict):
                    violations.append(
                        f"{page_path}: sources entries must be flat strings, "
                        f"got nested mapping: {s!r}"
                    )
                elif not isinstance(s, str):
                    violations.append(
                        f"{page_path}: sources entries must be strings, got {s!r}"
                    )

    # Phase B: quality block
    VALID_RATED_BY = {"ingester", "doctor", "human"}
    QUALITY_SCORE_FIELDS = ("accuracy", "completeness", "signal", "interlinking")
    if "quality" not in data:
        violations.append(f"{page_path}: missing required field: quality")
    else:
        q = data["quality"]
        if not isinstance(q, dict):
            violations.append(f"{page_path}: quality must be a nested mapping")
        else:
            for field in QUALITY_SCORE_FIELDS:
                if field not in q:
                    violations.append(f"{page_path}: missing quality.{field}")
                else:
                    v = q[field]
                    if not isinstance(v, int) or not (1 <= v <= 5):
                        violations.append(
                            f"{page_path}: quality.{field} must be int 1..5, got {v!r}"
                        )
            if "overall" not in q:
                violations.append(f"{page_path}: missing quality.overall")
            else:
                try:
                    scores = [q[f] for f in QUALITY_SCORE_FIELDS if isinstance(q.get(f), int)]
                    if len(scores) == 4:
                        expected = round(sum(scores) / 4, 2)
                        actual = float(q["overall"])
                        if abs(expected - actual) > 1e-6:
                            violations.append(
                                f"{page_path}: quality.overall must be mean of four "
                                f"scores rounded to 2 decimals. expected={expected}, "
                                f"got={actual}"
                            )
                except (TypeError, ValueError):
                    violations.append(f"{page_path}: quality.overall not numeric")
            if "rated_at" not in q:
                violations.append(f"{page_path}: missing quality.rated_at")
            else:
                v = q["rated_at"]
                if not isinstance(v, str) or not ISO_UTC_RE.match(v):
                    violations.append(
                        f"{page_path}: quality.rated_at must be ISO-8601 UTC, got {v!r}"
                    )
            if "rated_by" not in q:
                violations.append(f"{page_path}: missing quality.rated_by")
            else:
                v = q["rated_by"]
                if v not in VALID_RATED_BY:
                    violations.append(
                        f"{page_path}: quality.rated_by must be one of "
                        f"{sorted(VALID_RATED_BY)}, got {v!r}"
                    )

    # Wiki-root-mode additional checks
    if wiki_root is not None:
        # Body markdown link resolution
        # Body starts AFTER the closing ---
        body_split = text.split("\n---\n", 1)
        body = body_split[1] if len(body_split) == 2 else ""
        for link in _extract_body_links(body):
            if _is_external(link):
                continue
            # Strip any #anchor suffix
            link_clean = link.split("#", 1)[0]
            if link_clean == "":
                continue
            # v2.3: leading "/" resolves from wiki root, not page directory.
            if wiki_root is not None and link_clean.startswith("/"):
                target = (wiki_root / link_clean.lstrip("/")).resolve()
            else:
                target = (page_path.parent / link_clean).resolve()
            if not target.exists():
                violations.append(
                    f"{page_path}: broken markdown link: {link}"
                )

        # Sources existence
        if "sources" in data and isinstance(data["sources"], list):
            for s in data["sources"]:
                if not isinstance(s, str):
                    continue
                if s == "conversation":
                    # Phase B origin-tracking rules govern this; not a
                    # filesystem check.
                    continue
                src_path = (wiki_root / s).resolve()
                if not src_path.exists():
                    violations.append(
                        f"{page_path}: sources entry does not exist on disk: {s}"
                    )

    return violations


def main() -> int:
    argv = sys.argv[1:]
    wiki_root: Optional[Path] = None
    if argv and argv[0] == "--wiki-root":
        if len(argv) < 3:
            print("usage: wiki-validate-page.py [--wiki-root ROOT] <page>",
                  file=sys.stderr)
            return 1
        wiki_root = Path(argv[1]).resolve()
        page = Path(argv[2]).resolve()
        if not wiki_root.is_dir():
            print(f"not a directory: {wiki_root}", file=sys.stderr)
            return 1
    elif len(argv) == 1:
        page = Path(argv[0])
    else:
        print("usage: wiki-validate-page.py [--wiki-root ROOT] <page>",
              file=sys.stderr)
        return 1

    # Fail-fast on Python < 3.11 (stay consistent with wiki-init.sh).
    if sys.version_info < (3, 11):
        print("python 3.11+ required", file=sys.stderr)
        return 1

    # v2.3 I-1: catch caller-error case (page outside wiki root) cleanly.
    if wiki_root is not None:
        try:
            page.resolve().relative_to(wiki_root)
        except ValueError:
            print(f"error: {page} is not under wiki-root {wiki_root}", file=sys.stderr)
            return 1

    disc = None
    if wiki_root:
        try:
            disc = _discover(wiki_root)
        except RuntimeError as e:
            print(str(e), file=sys.stderr)
            return 1

    violations = validate(page, wiki_root, disc)
    if not violations:
        return 0
    for v in violations:
        print(v, file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
